name: 🐛 Bug Report
description: Report a problem to help us improve the project.
title: "[Bug] "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Description  
        Please provide a clear and concise description of the bug.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: "Describe the bug in detail."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: "List the steps to reproduce the bug."
      placeholder: |
        1. Go to "..."
        2. Click on "..."
        3. See the error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: "Describe what you expected to happen."
      placeholder: "What was the expected outcome?"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: "Example: macOS, Chrome 120, master branch"
      placeholder: "OS, browser, project version"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "Paste screenshots here (if applicable)."
      placeholder: "Drag and drop images or paste links."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: "Add any other information that may help."
      placeholder: "Any other relevant context."
    validations:
      required: false
