name: 🐛 Bug Report
description: Report a problem to help us improve the project.
title: "[Bug] "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Description
        Please provide a clear and concise description of the bug.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: Describe the bug in detail.
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See the error
      description: List the steps to reproduce the bug.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      placeholder: Describe what you expected to happen.
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, browser, project version
      description: Example: macOS, Chrome 120, master branch
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: Paste screenshots here (if applicable).
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      placeholder: Add any other information here.
    validations:
      required: false
