name: 🚀 Feature Request
description: Suggest an idea to improve this project.
title: "[Feature] "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        Provide a clear and concise description of the feature you want to request.

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      placeholder: Describe the feature in detail.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this feature needed?
      placeholder: Explain why this feature should be added.
    validations:
      required: true

  - type: textarea
    id: possible_implementation
    attributes:
      label: Possible Implementation
      placeholder: Suggest how it might be implemented.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      placeholder: Add any references, links, or screenshots.
    validations:
      required: false
